### ISSUE TITLE
Any way to convert 1 code (not a file)?

### ISSUE THREAD

**Issue by hepcat72** [sseshan1/globacache-broadlink#1]
I registered and verified a global cache account, but I can't seem to get it to send me an entire codeset.  It has sent me individual codes, but I don't know how to put those into a file that your tool accepts.  So is there a way to convert a code like this to a broadlink IR code?
```
INPUT HDMI 1

code1: sendir,1:1,1,38000,1,69,343,172,21,22,21,22,21,65,21,22,21,22,21,22,21,22,21,22,21,65,21,65,21,22,21,65,21,65,21,65,21,65,21,65,21,22,21,65,21,65,21,65,21,22,21,22,21,65,21,65,21,65,21,22,21,22,21,22,21,65,21,65,21,22,21,22,21,1673,343,86,21,3732

hex code1: 0000 006D 0022 0002 0157 00AC 0015 0016 0015 0016 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0016 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0016 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0016 0015 0016 0015 0689 0157 0056 0015 0E94
```

**Comment by hepcat72** [comment]
I have a few that I want to convert. And I'm hoping that the codes are compatible with a broadlink rm mini 3...

**Comment by sseshan1** [comment]
Robert,
For the individual commands, I recommend that you gather them in a file and
edit the lines so that they match the globalcache file format. For example,
your input line would become

"HDMI
1","sendir,1:1,1,38000,1,69,343,172,21,22,21,22,21,65,21,22,21,22,21,22,21,22,21,22,21,65,21,65,21,22,21,65,21,65,21,65,21,65,21,65,21,22,21,65,21,65,21,65,21,22,21,22,21,65,21,65,21,65,21,22,21,22,21,22,21,65,21,65,21,22,21,22,21,1673,343,86,21,3732",,

Notice that the command name and the command themselves are quote protected
and the two commas at the end of the line. Also clean out the command name
to make it more meaningful and avoid any punctuation characters if
possible.

Once you run the file through the python command and the awk scripts they
are compatible with the RM mini 3 which is what I use at home.

Good luck!

**Comment by hepcat72** [comment]
That worked!  Thank you so much!  (I didn't need to `awk` script, as I don't use mqtt - I just paste the codes into the homebridge config.)  :shipit:

PS - I should have just looked in your example input file. D'oh!
